### ISSUE TITLE
TAG_PATH ERROR

### ISSUE THREAD

**Issue by iroan** [jpush/jpush-api-nodejs-client#60]
`Push Fail, HttpStatusCode: 404 result: {"error":{"code":7010,"message":"request api doesn't exist"}}
Error
    at new APIRequestError (node_modules/jpush-async/lib/JPush/JPushError.js:25:17)
    at _request (node_modules/jpush-async/lib/JPush/JPushAsync.js:314:13)`
`node_modules/jpush-async/lib/JPush/JPushAsync.js:23`

it should be:
`var TAG_PATH = '/v3/tags/'`

**Comment by baipeng1009472720** [comment]
我也遇到这个问题

**Comment by helperhaps** [comment]
已解决，请升级到 4.0.2

**Comment by baipeng1009472720** [comment]
吼得
